# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-20 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='学号')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('gender', models.CharField(default='', max_length=50, null=True, verbose_name='性别')),
                ('phone', models.CharField(default='', max_length=50, null=True, verbose_name='手机号')),
                ('email', models.EmailField(default='', max_length=200, null=True, verbose_name='邮箱')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('img_img', models.CharField(default='', max_length=50, null=True, verbose_name='新密码')),
                ('img_gender', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('image_name', models.CharField(default='', max_length=50, null=True, verbose_name='性别')),
                ('img_addr', models.CharField(default='', max_length=200, null=True, verbose_name='籍贯')),
                ('img_sfz', models.CharField(default='', max_length=200, null=True, verbose_name='身份证号')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user_info',
            },
        ),
    ]
