# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-01 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200430_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yyzz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(default='', null=True, upload_to='img', verbose_name='图片路径')),
                ('dwmc', models.CharField(default='', max_length=200, null=True, verbose_name='单位名称')),
                ('fr', models.CharField(default='', max_length=200, null=True, verbose_name='法人')),
                ('dz', models.CharField(default='', max_length=200, null=True, verbose_name='地址')),
                ('clrq', models.CharField(default='', max_length=200, null=True, verbose_name='成立日期')),
                ('jyfw', models.CharField(default='', max_length=500, null=True, verbose_name='经营范围')),
                ('lx', models.CharField(default='', max_length=200, null=True, verbose_name='类型')),
                ('yxq', models.CharField(default='', max_length=200, null=True, verbose_name='有效期')),
                ('zcxs', models.CharField(default='', max_length=200, null=True, verbose_name='组成形式')),
                ('zjbh', models.CharField(default='', max_length=200, null=True, verbose_name='证件编号')),
                ('shxydm', models.CharField(default='', max_length=200, null=True, verbose_name='社会信用代码')),
                ('zczb', models.CharField(default='', max_length=200, null=True, verbose_name='注册资本')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yyzz_user', to='myapp.User')),
            ],
            options={
                'verbose_name': '营业执照信息',
                'verbose_name_plural': '营业执照信息',
                'db_table': 'yyzz_info',
            },
        ),
    ]
