# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-01 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_yyzz'),
    ]

    operations = [
        migrations.AddField(
            model_name='yyzz',
            name='status',
            field=models.CharField(choices=[('未通过', '未通过'), ('通过', '通过')], default='未通过', max_length=50, verbose_name='审核状态'),
        ),
    ]
