# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-01 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_yyzz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yyzz',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yyzz_user', to='myapp.User'),
        ),
    ]
